<?php

namespace PeopleBundle\Repository;

/**
 * PilotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PilotRepository extends \Doctrine\ORM\EntityRepository
{
}
