<?php

namespace CarBundle\Repository;

/**
 * CarBrandTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarBrandTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
