<?php

namespace CarBundle\Repository;

/**
 * CarFuelTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarFuelTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
