<?php

namespace CarBundle\Repository;

/**
 * CarModelTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarModelTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
