<?php

namespace RideBundle\Repository;

/**
 * GPSPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GPSPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
