<?php

namespace RideBundle\Repository;

/**
 * RideStatusTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RideStatusTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
